---
title: "Untitled"
author: "Phil Kaplan"
date: "2024-02-14"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r functions, message=FALSE, echo=FALSE, warning=FALSE}
dat1 <- tibble(
 Person= c("Phil", "Colin", "Michael"),
  Mmuscle = c(0.418, 0.252, 0.344),
  Lo = c(0.320, 0.280, 0.320),
  Li = c(0.080, 0.065, 0.080),
  Larm = c(0.350, 0.31, 0.305)
)
print(dat1)
```

```{r}
#Writing Needed Functions 

#Insertion angles
law_cos <- function(o, l, r) {
  acos((-o^2 + l^2 + r^2) / (2 * l * r))
}


law_cos2 <- function(l, r, theta) {
  sqrt(l^2 + r^2 - 2 * l * r * cos(theta))
}

#Establishing rho, k, and g 
rho <- 0.00105
k <- 80
g <- 9.81 

ffl <- function(Lmuscle, Lmuscler) {
  -6.25 * ((Lmuscle / Lmuscler)^2) + 12.5 * (Lmuscle / Lmuscler) - 5.25
}

# Function to calculate PCSA and Fmax
PCSA <- function(Mmuscle, phi, Lmuscler) {
  Mmuscle * cos(phi) / (rho * Lmuscler)
}


```

```{r functions, message=FALSE, echo=FALSE, warning=FALSE}

model <- function(mass, Lmuscler, Lmuscle, theta, Lo, rho = 0.00105, k = 80) {
  Lmuscler_cm <- Lmuscler * 100 
  Lmuscle_cm <- Lmuscle * 100  
  Lo_cm <- Lo * 100  
  
  pcsa <- PCSA(mass, 0, Lmuscler_cm) 
  Fmax <- pcsa * k  
  
  ffl_value <- ffl(Lmuscle_cm, Lmuscler_cm * 0.8)  
  
  Fmuscle <- Fmax * ffl_value 
  
  torque <- Fmuscle * sin(theta) * Lo_cm 
  
  return(torque)
}

```

```{r}
#Final Data 

dat_updated <- dat1 %>%
  crossing(flexion = c(50, 75, 100, 125, 150) * pi / 180) %>%
  rowwise() %>%
  mutate(
    Lmuscle = law_cos2(Larm, Li, flexion),
    theta = law_cos(Larm, Li, Lmuscle)
  ) %>%
  ungroup()

# Apply the model function to calculate muscle_torque
dat_with_torque <- dat_updated %>%
  mutate(
    muscle_torque = model(Mmuscle, Larm, Lmuscle, theta, Lo),
    max_mass = muscle_torque / (Lo * 100 * g)  
  )

# View the final tibble
print(dat_with_torque)
```

